### ISSUE TITLE
Estrutura de diretórios

### ISSUE THREAD

**Issue by alexandre-mbm** [santamariense/cnefe#3]
Atualmente nós temos o seguinte:
```
└── cnefe
    ├── LICENSE
    ├── Pictures
    │   └── *.png
    ├── Relatório de caso CNEFE em SM. Proposta 1.md
    └── Relatório de caso CNEFE em SM. Proposta 1.osm
```
Poderia ser assim:
```
└── cnefe
    └── Relatório de caso CNEFE em SM. Proposta 1
         ├── LICENSE
         ├── img
         │   └── *.png
         ├── README.md
         └── data.osm
```
Isso tem a vantagem de renderizar os arquivos README na web do GitHub.

O que acha?

**Comment by santamariense** [comment]
Acho que fica bom. Quero ver se monto um relatório da Proposta 2 ainda.

**Comment by alexandre-mbm** [comment]
Farei as mudanças, também renomeado as imagens. Pretendo submeter o _pull request_ hoje à noite.

**Comment by alexandre-mbm** [comment]
Aceite lá!
